### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by adswa** [datalad/git-annex-ria-remote#35] opened 2019-12-11 08:23 UTC
How do you prefer to have this cited in an OHBM abstract? Would
``Poldrack, B. & Hanke, M., ria-remote 0.6.1, https://github.com/datalad/git-annex-ria-remote `` suffice?

**Comment by mih** [comment] 2020-06-19 05:19
Closing issue, repository will be archived. If further discussion is needed, please check whether the issue is still present in DataLad 0.13* and file a new issue at https://github.com/datalad/datalad

**Closed as completed by mih** 2020-06-19 05:19 UTC
