### ISSUE TITLE
Missing publication dependency to ria sibling in dataset clone

### ISSUE THREAD

**Issue by adswa** [datalad/git-annex-ria-remote#46] opened 2020-02-12 10:48 UTC
When cloning a dataset from a RIA store, publishing back to the RIA store (origin) requires a separate publish to the ria-special remote sibling, i.e. the publication dependency that gets created with `create-sibling-ria` in the original dataset does not exist in a clone of the dataset from the store -- Only when publishing explicitly to the ria sibling the contents are pushed to the store. It would be cool to have a publication dependency automatically set up, so that no one needs to even know about the special remote sibling.

Example of the problem: 
SSH access RIA store on juseless, working in clone from RIA store locally.

```sh
╭─adina@muninn ~/repos/talks/inm1talk on master
╰─➤ datalad siblings                                                                                      130 ↵
.: here(+) [git]
.: juseless-ria(+) [ria]
.: origin(-) [ssh://juseless.inm7.de/data/group/psyinf/dataset_store/946/e8cac-432b-11ea-aac8-f0d5bf7b5561 (git)]
╭─adina@muninn ~/repos/talks/inm1talk on master
╰─➤ touch file1
╭─adina@muninn ~/repos/talks/inm1talk on master
╰─➤ datalad save -m "TMP: adding a random file to test for a bug"
add(ok): file1 (file)                                                           
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
╭─adina@muninn ~/repos/talks/inm1talk on master
╰─➤ datalad publish --transfer-data all
publish(ok): . (dataset) [pushed to origin: ['8466b5b..01fc098', '26eb7af..7a2ecd4']]

```
If I ``update --merge`` in a second clone of the same dataset, the file is not in the RIA store's annex:

```
adina@juseless in ~/946e8cac-432b-11ea-aac8-f0d5bf7b5561 on git:master
❱ datalad update --merge
[INFO   ] Fetching updates for <Dataset path=/home/adina/946e8cac-432b-11ea-aac8-f0d5bf7b5561> 
[INFO   ] Applying updates to <Dataset path=/home/adina/946e8cac-432b-11ea-aac8-f0d5bf7b5561> 
update(ok): . (dataset)
adina@juseless in ~/946e8cac-432b-11ea-aac8-f0d5bf7b5561 on git:master
❱ ls
datalad2h.webm  file1  proc  README  rec  talk.kdenlive  talk.mp4  talk.webm
adina@juseless in ~/946e8cac-432b-11ea-aac8-f0d5bf7b5561 on git:master
❱ git annex whereis file1
whereis file1 (1 copy) 
  	99ba6ef6-883e-4353-af77-e88ba5dc165f -- adina@muninn:~/repos/talks/inm1talk
ok
```

ping @bpoldrack

**Comment by bpoldrack** [comment] 2020-02-12 14:39
As we currently move the entirety of `git-annex-ria-remote` to datalad core, this is already addressed in https://github.com/datalad/datalad/pull/4099/, i.e. when `datalad-clone` from a `ria+file://` or `ria+http://` address. At least I hope so - I'd be happy to hear whether that works as you want it ;-)

**Comment by mih** [comment] 2020-06-19 05:18
Closing issue, repository will be archived. If further discussion is needed, please check whether the issue is still present in DataLad 0.13* and file a new issue at https://github.com/datalad/datalad

**Closed as completed by mih** 2020-06-19 05:18 UTC
