### ISSUE TITLE
store.datalad.org requires HTTP IO

### ISSUE THREAD

**Issue by bpoldrack** [datalad/git-annex-ria-remote#41] opened 2020-01-15 08:30 UTC
We need an `HTTPRemoteIO` class (similar to `SSHRemoteIO`), to access non-archived annex keys via http.
  - should this be read-only or would we want to allow to upload as well?
  - what's the criterion to switch to this one rather than SSH?

Ping @mih

**Comment by mih** [comment] 2020-06-19 05:19
Closing issue, repository will be archived. If further discussion is needed, please check whether the issue is still present in DataLad 0.13* and file a new issue at https://github.com/datalad/datalad

**Closed as completed by mih** 2020-06-19 05:19 UTC
