### ISSUE TITLE
SSHRemoteIO.get() needs robustness

### ISSUE THREAD

**Issue by bpoldrack** [datalad/git-annex-ria-remote#21] opened 2019-09-04 07:04 UTC
Currently we will hang forever if the file isn't readable and it's supposed size is bigger than whatever cat spits out on stdout. This is because we don't notice that cat has exited non-zero. We could have end marker on stderr instead, but then we need to empty stderr beforehand to not act upon output from earlier calls. This is a problem with blocking reading, since we need to make sure there's actually something to read in any case.

For the implications about stderr, this is closely related to #20

Ultimately it seems pretty clear, that we need to switch to asyncio or sth.

**Comment by mih** [comment] 2020-06-19 05:19
Closing issue, repository will be archived. If further discussion is needed, please check whether the issue is still present in DataLad 0.13* and file a new issue at https://github.com/datalad/datalad

**Closed as completed by mih** 2020-06-19 05:19 UTC
