### ISSUE TITLE
deduplication: export_archive should use RiaRemote

### ISSUE THREAD

**Issue by bpoldrack** [datalad/git-annex-ria-remote#27] opened 2019-11-12 10:45 UTC
Not incredibly important until an actual change in layout, but:
`export_archives` currently determines hasdir/key paths on it's own. Probably should import `RiaRemote` instead and make use of its `get_obj_location`.

**Comment by mih** [comment] 2019-11-12 10:49
That won't work, because this helper requires a running git-annex to talk to. But we could do it the other way round. I am somewhat confident that a pure-Python solution is faster than IPC with git-annex.

**Comment by bpoldrack** [comment] 2019-11-23 17:19
reopened in light of my comments on PR #31 

>    this helper requires a running git-annex to talk to

I don't think so. `get_obj_location` is a staticmethod. 

Edit:

Nope. `get_layout_locations` is what I'm talking about. It doesn't get the key path, but we don't need that ATM.

**Comment by mih** [comment] 2020-06-19 05:19
Closing issue, repository will be archived. If further discussion is needed, please check whether the issue is still present in DataLad 0.13* and file a new issue at https://github.com/datalad/datalad

**Closed as completed by mih** 2020-06-19 05:19 UTC
