### ISSUE TITLE
export-archive doc is out dated

### ISSUE THREAD

**Issue by bpoldrack** [datalad/git-annex-ria-remote#40] opened 2020-01-15 08:28 UTC
We don't use hashdirlower anymore. But `export-archive`'s doc says we do.

**Comment by mih** [comment] 2020-06-19 05:19
Closing issue, repository will be archived. If further discussion is needed, please check whether the issue is still present in DataLad 0.13* and file a new issue at https://github.com/datalad/datalad

**Closed as completed by mih** 2020-06-19 05:19 UTC
