### ISSUE TITLE
Tests failed to pick up a hanging 'get'

### ISSUE THREAD

**Issue by bpoldrack** [datalad/git-annex-ria-remote#30] opened 2019-11-19 16:09 UTC
SSH remote failed to properly fail on a get to non-existing annex/object/<somekey>, leading to hang the entire thing, when should have raised and then looked for it in the archive.

Fixed the actual issue here:
https://github.com/datalad/git-annex-ria-remote/pull/28/commits/15c82a5a0fb0cfc1e13504b42e5725834709361a

However, tests should have picked that one up and didn't. Hence the need to double check SSH testing.

**Comment by mih** [comment] 2020-06-19 05:19
Closing issue, repository will be archived. If further discussion is needed, please check whether the issue is still present in DataLad 0.13* and file a new issue at https://github.com/datalad/datalad

**Closed as completed by mih** 2020-06-19 05:19 UTC
